server:
  port: 8083

spring:
  config:
    import: optional:configserver:instead/
    enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservicios

  application:
    name: CALIFICACION-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka