server:
  port: 8086

spring:
  application:
    name: AUTH-SERVICE
  config:
    import: optional:configserver:http://localhost:8085

jwt:
  secret: secret

admin-paths:
  paths:
    -
      uri: "/usuarios"
      method: "POST"
